export const initialInventory = [
  {
    id: 1,
    item: 'Aren Sugar',
    quantity: 0,
    uom: 'kg',
    price: 60000,
    label: '15 g of aren sugar:',
  },
  {
    id: 2,
    item: 'Milk',
    quantity: 0,
    uom: 'Liter',
    price: 30000,
    label: '150 ml of milk:',
  },
  {
    id: 3,
    item: 'Ice Cube',
    quantity: 0,
    uom: 'Kg',
    price: 15000,
    label: '20 g of ice cube:',
  },
  {
    id: 4,
    item: 'Plastic Cup',
    quantity: 0,
    uom: 'pcs',
    price: 500,
    label: '1 pcs of plastic cup:',
  },
  {
    id: 5,
    item: 'Coffee Bean',
    quantity: 0,
    uom: 'kg',
    price: 100000,
    label: '20 g of coffee bean:',
  },
  {
    id: 6,
    item: 'Mineral Water',
    quantity: 0,
    uom: 'Liter',
    price: 5000,
    label: '50 ml of mineral water:',
  },
];
